# version 1
name: Testing Flight Validation
on: push

jobs:
  test_flight_validation:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: airlinex_db
          POSTGRES_USER: airlinex_user
          POSTGRES_PASS: airlinex_pass
        ports:
          - "5432:5432"
      options: >-
        --health-cmd "pg_isready -U airlinex_user -d airlinex_db"
        --health-interval 5s
        --health-timeout 5s
        --health-retries 5
        
    env:
      ENGINE: django.db.backends.postgresql
      DB_NAME: airlinex_db
      DB_USER: airlinex_user
      DB_PASSWORD: airlinex_pass
      DB_HOST: localhost
      DB_PORT: 5432
    

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12
          cache: pip
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Unit Tests
        run: python3 manage.py test
